name: docker-build-base

on:
  workflow_dispatch:
    inputs:
      push:
        description: 'wether to push the docer image afterwards'
        required: true
        default: 'true'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure docker
        run: |
          sudo bash -c 'echo "{\"experimental\": true}" >> /etc/docker/daemon.json'
          sudo systemctl restart docker

      - name: Make docker image
        run: make docker-build-base
