# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      LOCALSTACK_DIR: ${{ github.workspace }}/localstack

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Output environment
        run: |
          echo ${{ github.workspace }}
          ls -la
          env
          which python || true
          python --version || true
          which python3 || true
          python3 --version || true          

      - name: Checkout localstack
        run: |
          git clone https://github.com/localstack/localstack ${LOCALSTACK_DIR}
          cd ${LOCALSTACK_DIR}
          ln -s ${{ github.workspace }}/localstack_ext .
          ls -la

      - name: Build localstack
        run: |
          sudo apt-get update
          sudo apt-get install -y libsasl2-dev python3.8-venv python3.8-dev

          cd ${LOCALSTACK_DIR}
          python3 -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install wheel setuptools pytest
          pip install -r requirements.txt
          pip uninstall localstack-ext
          python -m localstack.services.install libs
          python -m localstack.services.install testlibs
          mkdir -p target/reports

      - name: Run tests
        run: |
          cd ${LOCALSTACK_DIR}
          source .venv/bin/activate
          DEBUG=1 LOCALSTACK_API_KEY=test PYTEST_ARGS="--junitxml=target/reports/unit.xml -o junit_suite_name='unit'" TEST_PATH='tests/unit' make test
