name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-10.15, windows-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Debug
        run: bash bin/multi-platform.sh

  release:
    needs: build
    runs-on: ubuntu-latest
    run:
      pwd
      ls -la
