name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  # build:
  #   runs-on: ${{ matrix.os }}

  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest]

  #   steps:
  #     - name: Check out Git repository
  #       uses: actions/checkout@v1

  #     - name: Debug
  #       run: bash bin/multi-platform.sh

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install
        run: sudo apt-get install tree

      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: List directory
        run: |
          pwd
          ls -la
          tree -a

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: List directory
        run: |
          pwd
          ls -la
          tree -a
