name: Release

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Release type'
        default: 'dev'
        type: choice
        options:
        - dev
        - patch
        - minor
        - major


jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Log environment"
        env:
          RELEASE_TYPE: ${{ inputs.releaseType }}
        run: |
          echo "Release type: ${RELEASE_TYPE}"
          echo "Github Actor: ${GITHUB_ACTOR}"
          echo "Githu Ref: ${GITHUB_REF}"

      - name: "Increment release"
        env:
          RELEASE_TYPE: ${{ inputs.releaseType }}
        run: |
          echo "${RELEASE_TYPE}" >> CHANGELOG

      - name: "Commit release version"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # Optional. Commit message for the created commit.
          # Defaults to "Apply automatic changes"
          commit_message: "Release version v"
          create_branch: true
          branch: release-test

          add_options: '--all'

          # Optional commit user and author settings
          #commit_user_name: localstack-bot # defaults to "github-actions[bot]"
          #commit_user_email: my-github-actions-bot@example.org # defaults to "github-actions[bot]@users.noreply.github.com"
          #commit_author: LocalStack Bot <actions@github.com> # defaults to author of the commit that triggered the run

          # Optional. Tag name being created in the local repository and 
          # pushed to remtoe repository and defined branch.
          #tagging_message: 'v1.0.0'
      
      - name: "Git Log"
        run: |
          git log -n 2
