name: Release

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Release type'
        default: 'dev'
        type: choice
        options:
        - dev
        - patch
        - minor
        - major


jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Compute release versions"
        env:
          RELEASE_TYPE: ${{ inputs.releaseType }}
        run: |
          bin/release.sh save-env ${RELEASE_TYPE}

      - name: "Explain release steps"
        env:
          RELEASE_TYPE: ${{ inputs.releaseType }}
        run: |
          bin/release.sh explain-steps

      # - name: "Commit release version"
      #   run: |
      #     git config user.name "github-actions[bot]"
      #     git config user.email "github-actions[bot]@users.noreply.github.com"
      #     git add .
      #     git commit -m "Release version v?"
      #     git push
      
      - name: "Git Log"
        run: |
          git log -n 2
